[db]
# Database connection string
url = mysql://user:password@localhost:3306/api_balance

# Location of your models
models = ["app.models"]

# Location to store migration files
location = ./migrations

# If true, will use 'IF NOT EXISTS' when creating tables
safe = True
